// ignore_for_file: type=lint

// Generated file; DO NOT EDIT!
// Generated by tools/generate_device_info.dart on 2022-07-13 14:15:54.569674Z (using razer-macos 345cb5ef609f0e4b276e89f4103074e76a30b9ef).

/// The type of device described by a [RazerDeviceInfo] instance.
enum RazerDeviceType {
  headphone,
  egpu,
  mousedock,
  accessory,
  mouse,
  keyboard,
  mousemat
}

/// Features that are unsupported by some devices.
enum OptionalRazerDeviceFeature {
  spectrum,
  ripple,
  none,
  reactive,
  waveSimple,
  oldMouseEffects,
  mouseBrightness,
  battery,
  wheel,
  breathe
}

/// Device-specific configuration values for a feature.
class RazerDeviceFeatureConfig {
  const RazerDeviceFeatureConfig();
}

class DpiFeatureConfig extends RazerDeviceFeatureConfig {
  const DpiFeatureConfig({required this.max});

  final int max;
}

class MouseBrightnessFeatureConfig extends RazerDeviceFeatureConfig {
  const MouseBrightnessFeatureConfig(
      {this.enabledMatrix,
      this.enabledScroll,
      this.enabledLeft,
      this.enabledRight,
      this.enabledLogo});

  final bool? enabledMatrix;

  final bool? enabledScroll;

  final bool? enabledLeft;

  final bool? enabledRight;

  final bool? enabledLogo;
}

class StaticFeatureConfig extends RazerDeviceFeatureConfig {
  const StaticFeatureConfig({required this.enabledRed});

  final bool enabledRed;
}

class OldMouseEffectsFeatureConfig extends RazerDeviceFeatureConfig {
  const OldMouseEffectsFeatureConfig({required this.enabledScroll});

  final bool enabledScroll;
}

class RippleFeatureConfig extends RazerDeviceFeatureConfig {
  const RippleFeatureConfig({required this.rows, required this.cols});

  final int rows;

  final int cols;
}

class WheelFeatureConfig extends RazerDeviceFeatureConfig {
  const WheelFeatureConfig({required this.rows, required this.cols});

  final int rows;

  final int cols;
}

/// Information about a Razer Chroma device.
class RazerDeviceInfo {
  const RazerDeviceInfo(
      {required this.name,
      required this.productId,
      required this.mainType,
      required this.image,
      required this.missingFeatures,
      required this.featureConfigs});

  final String name;

  final int productId;

  final RazerDeviceType mainType;

  final String image;

  final Set<OptionalRazerDeviceFeature> missingFeatures;

  final Map<Type, RazerDeviceFeatureConfig> featureConfigs;

  /// A map of USB product IDs to Razer Chroma device information.
  static const products = {
    0x42: RazerDeviceInfo(
        name: 'Razer Abyssus',
        productId: 0x42,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/274/abyssus2014_500x500.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {}),
    0x20: RazerDeviceInfo(
        name: 'Razer Abyssus 1800',
        productId: 0x20,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1277/1277_abyssus_2000.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 1800)}),
    0x5e: RazerDeviceInfo(
        name: 'Razer Abyssus 2000',
        productId: 0x5e,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1277/1277_abyssus_2000.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 2000)}),
    0x6a: RazerDeviceInfo(
        name: 'Razer Abyssus Elite DVA Edition',
        productId: 0x6a,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1288/d.va_abyssus_elite.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 7200)
        }),
    0x6b: RazerDeviceInfo(
        name: 'Razer Abyssus Essential',
        productId: 0x6b,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1290/1290_abyssusessential.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 7200)
        }),
    0x5b: RazerDeviceInfo(
        name: 'Razer Abyssus V2',
        productId: 0x5b,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/721/721_abyssusv2.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.none,
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.spectrum,
          OptionalRazerDeviceFeature.reactive,
          OptionalRazerDeviceFeature.breathe,
          OptionalRazerDeviceFeature.battery
        },
        featureConfigs: {
          StaticFeatureConfig: StaticFeatureConfig(enabledRed: false),
          OldMouseEffectsFeatureConfig:
              OldMouseEffectsFeatureConfig(enabledScroll: false),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 5000)
        }),
    0x10f: RazerDeviceInfo(
        name: 'Razer Anansi',
        productId: 0x10f,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/54/54_anansi.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x62: RazerDeviceInfo(
        name: 'Razer Atheris (Receiver)',
        productId: 0x62,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1234/1234_atheris.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 7200)}),
    0xf20: RazerDeviceInfo(
        name: 'Razer Base Station V2 Chroma',
        productId: 0xf20,
        mainType: RazerDeviceType.accessory,
        image: 'https://dl.razerzone.com/src/3897-1-EN-v2.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x64: RazerDeviceInfo(
        name: 'Razer Basilisk',
        productId: 0x64,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1241/1241_basilisk.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 16000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false)
        }),
    0x65: RazerDeviceInfo(
        name: 'Razer Basilisk Essential',
        productId: 0x65,
        mainType: RazerDeviceType.mouse,
        image:
            'https://hybrismediaprod.blob.core.windows.net/sys-master-phoenix-images-container/h19/h61/9080617500702/Basilisk-Essential-500x500.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.oldMouseEffects
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 6400),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false)
        }),
    0x86: RazerDeviceInfo(
        name: 'Razer Basilisk Ultimate',
        productId: 0x86,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1590/1590_basilisk_ultimate.png',
        missingFeatures: {},
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig:
              MouseBrightnessFeatureConfig(enabledMatrix: false)
        }),
    0x88: RazerDeviceInfo(
        name: 'Razer Basilisk Ultimate Receiver',
        productId: 0x88,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1590/1590_basilisk_ultimate.png',
        missingFeatures: {},
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig:
              MouseBrightnessFeatureConfig(enabledMatrix: false)
        }),
    0x85: RazerDeviceInfo(
        name: 'Razer Basilisk V2',
        productId: 0x85,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1617/1617_basilisk-v2.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false)
        }),
    0x99: RazerDeviceInfo(
        name: 'Razer Basilisk V3',
        productId: 0x99,
        mainType: RazerDeviceType.mouse,
        image: 'https://dl.razerzone.com/src/5620/5620-1-en-v1.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.oldMouseEffects,
          OptionalRazerDeviceFeature.reactive,
          OptionalRazerDeviceFeature.battery,
          OptionalRazerDeviceFeature.breathe
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 26000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false)
        }),
    0x241: RazerDeviceInfo(
        name: 'Razer BlackWidow 2019',
        productId: 0x241,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1501/1501-blackwidow2019.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x203: RazerDeviceInfo(
        name: 'Razer BlackWidow Chroma',
        productId: 0x203,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/279/279_blackwidow_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x209: RazerDeviceInfo(
        name: 'Razer BlackWidow Chroma Tournament Edition',
        productId: 0x209,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/571/571_blackwidow_tournament_edition_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x221: RazerDeviceInfo(
        name: 'Razer BlackWidow Chroma V2',
        productId: 0x221,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1179/1179_blackwidow_chroma_v2_alt.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x228: RazerDeviceInfo(
        name: 'Razer BlackWidow Elite',
        productId: 0x228,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1398/1398_blackwidowelite.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x237: RazerDeviceInfo(
        name: 'Razer BlackWidow Essential',
        productId: 0x237,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1501/1501-blackwidow2019.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x235: RazerDeviceInfo(
        name: 'Razer BlackWidow Lite',
        productId: 0x235,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1456/1456_blackwidowlite_-_2.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x211: RazerDeviceInfo(
        name: 'Razer BlackWidow Overwatch',
        productId: 0x211,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/products/23326/overwatch-razer-gallery-5.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x11b: RazerDeviceInfo(
        name: 'Razer BlackWidow Stealth',
        productId: 0x11b,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/products/17559/razer-blackwidow-gallery-01.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x10e: RazerDeviceInfo(
        name: 'Razer BlackWidow Stealth Edition',
        productId: 0x10e,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/products/17559/razer-blackwidow-gallery-01.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x10d: RazerDeviceInfo(
        name: 'Razer BlackWidow Ultimate 2012',
        productId: 0x10d,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/563/563_blackwidow_ultimate_classic.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x11a: RazerDeviceInfo(
        name: 'Razer BlackWidow Ultimate 2013',
        productId: 0x11a,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/245/438_blackwidow_ultimate_2014.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x214: RazerDeviceInfo(
        name: 'Razer BlackWidow Ultimate 2016',
        productId: 0x214,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/616/616_blackwidow_ultimate_2016.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x24e: RazerDeviceInfo(
        name: 'Razer BlackWidow V3',
        productId: 0x24e,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1718/1718-blackwidowv3.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x25a: RazerDeviceInfo(
        name: 'Razer BlackWidow V3 Pro (Wired)',
        productId: 0x25a,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1709/1709-blackwidow-v3-tkl.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0xa24: RazerDeviceInfo(
        name: 'Razer BlackWidow V3 Tenkeyless',
        productId: 0xa24,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1709/1709-blackwidow-v3-tkl.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 18),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 18)
        }),
    0x216: RazerDeviceInfo(
        name: 'Razer BlackWidow X Chroma',
        productId: 0x216,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/716/716_blackwidow_x_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x21a: RazerDeviceInfo(
        name: 'Razer BlackWidow X Chroma Tournament Edition',
        productId: 0x21a,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/717/717_blackwidow_x_tournament_edition_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x217: RazerDeviceInfo(
        name: 'Razer BlackWidow X Ultimate',
        productId: 0x217,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/718/718_blackwidow_x_ultimate.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x233: RazerDeviceInfo(
        name: 'Razer Blade 15 (2018)',
        productId: 0x233,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1418/1418_blade_2018__base.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x23b: RazerDeviceInfo(
        name: 'Razer Blade 15 (2018) Base Model',
        productId: 0x23b,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1418/1418_blade_2018__base.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x240: RazerDeviceInfo(
        name: 'Razer Blade 2018 Mercury',
        productId: 0x240,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1552/1552-blade-stealth-mercury-white.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x23a: RazerDeviceInfo(
        name: 'Razer Blade 15 (2019) Advanced',
        productId: 0x23a,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1482/blade15.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x246: RazerDeviceInfo(
        name: 'Razer Blade 15 (2019) Base Model',
        productId: 0x246,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1518/1518_blade15_mid2019-base.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x224: RazerDeviceInfo(
        name: 'Razer Blade Late 2016',
        productId: 0x224,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/736/736_blade_pro_2016.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x245: RazerDeviceInfo(
        name: 'Razer Blade 15 (Mid 2019) Mercury White',
        productId: 0x245,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets2.razerzone.com/images/blade-15/shop/blade15-mercury-1.jpg',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 6),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 6)
        }),
    0x225: RazerDeviceInfo(
        name: 'Razer Blade Pro (2017)',
        productId: 0x225,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1200/1200_blade_pro_2017.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 25),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 25)
        }),
    0x22f: RazerDeviceInfo(
        name: 'Razer Blade Pro 2017 FullHD',
        productId: 0x22f,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1200/1200_blade_pro_2017.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 25),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 25)
        }),
    0x210: RazerDeviceInfo(
        name: 'Razer Blade Pro Late 2016',
        productId: 0x210,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/736/736_blade_pro_2016.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x20f: RazerDeviceInfo(
        name: 'Razer Blade Stealth (QHD)',
        productId: 0x20f,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/736/736_blade_pro_2016.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x205: RazerDeviceInfo(
        name: 'Razer Blade Stealth',
        productId: 0x205,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/667/667_blade_stealth_2016_6500u.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x239: RazerDeviceInfo(
        name: 'Razer Blade Stealth (2019)',
        productId: 0x239,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1475/1475_bladestealth13(2019).png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x220: RazerDeviceInfo(
        name: 'Razer Blade Stealth (Late 2016)',
        productId: 0x220,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/667/667_blade_stealth_2016_6500u.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x232: RazerDeviceInfo(
        name: 'Razer Blade Stealth (Late 2017)',
        productId: 0x232,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1213/1213_blade_stealth_2017_7500u.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x24a: RazerDeviceInfo(
        name: 'Razer Blade Stealth (Late 2019)',
        productId: 0x24a,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets2.razerzone.com/images/blade-stealth-13/shop/stealth-l2p-1.jpg',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x22d: RazerDeviceInfo(
        name: 'Razer Blade Stealth (Mid 2017)',
        productId: 0x22d,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1213/1213_blade_stealth_2017_7500u.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0x24d: RazerDeviceInfo(
        name: 'Razer Blade Studio Edition 2019',
        productId: 0x24d,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1575/1575_blade_15_late_2019_-_studio_edition-2.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 16),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 16)
        }),
    0xf08: RazerDeviceInfo(
        name: 'Razer Chroma Base',
        productId: 0xf08,
        mainType: RazerDeviceType.accessory,
        image:
            'https://rzrwarranty.s3.amazonaws.com/145dcc47f9f9d33b0bd07b066364704160f45e87b756d690b203decec7d1e87c.png',
        missingFeatures: {},
        featureConfigs: {}),
    0xf09: RazerDeviceInfo(
        name: 'Razer Chroma HDK',
        productId: 0xf09,
        mainType: RazerDeviceType.accessory,
        image:
            'https://assets2.razerzone.com/images/chromahdk2017/788b689d471fedbc0c5a175592316657-gallery-08.jpg',
        missingFeatures: {},
        featureConfigs: {}),
    0xf07: RazerDeviceInfo(
        name: 'Razer Chroma Mug',
        productId: 0xf07,
        mainType: RazerDeviceType.accessory,
        image:
            'https://assets2.razerzone.com/images/mug-holder/e64e507b73e61c44789d996065fd9645-1500x1000mug_01.jpg',
        missingFeatures: {},
        featureConfigs: {}),
    0xf1a: RazerDeviceInfo(
        name: 'Razer Core X Chroma',
        productId: 0xf1a,
        mainType: RazerDeviceType.egpu,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1506/1506_core_x_chroma.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x22a: RazerDeviceInfo(
        name: 'Razer Cynosa Chroma',
        productId: 0x22a,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1256/1256_cynosa_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x22c: RazerDeviceInfo(
        name: 'Razer Cynosa Chroma Pro',
        productId: 0x22c,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1257/1257_cynosa_chroma_pro_alt.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x23f: RazerDeviceInfo(
        name: 'Razer Cynosa Lite',
        productId: 0x23f,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets2.razerzone.com/images/og-image/cynosa-lite-OGimage.jpg',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x25e: RazerDeviceInfo(
        name: 'Razer Cynosa V2',
        productId: 0x25e,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1694/1694-2.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x38: RazerDeviceInfo(
        name: 'Razer DeathAdder 1800',
        productId: 0x38,
        mainType: RazerDeviceType.mouse,
        image:
            'https://rzrwarranty.s3.amazonaws.com/a7daf40ad78c9584a693e310effa956019cdcd081391f93f71a7cd36d3dc577e.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 1800)}),
    0x37: RazerDeviceInfo(
        name: 'Razer DeathAdder 2013',
        productId: 0x37,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/561/561_deathadder_classic.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 6400)}),
    0x54: RazerDeviceInfo(
        name: 'Razer DeathAdder 3500',
        productId: 0x54,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/561/561_deathadder_classic.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 3500)
        }),
    0x16: RazerDeviceInfo(
        name: 'Razer DeathAdder 3.5G',
        productId: 0x16,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-04.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 3500)}),
    0x43: RazerDeviceInfo(
        name: 'Razer DeathAdder Chroma',
        productId: 0x43,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/278/278_deathadder_chroma.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.none,
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.spectrum,
          OptionalRazerDeviceFeature.reactive,
          OptionalRazerDeviceFeature.breathe
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 10000)
        }),
    0x5c: RazerDeviceInfo(
        name: 'Razer DeathAdder Elite',
        productId: 0x5c,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/724/724_deathadderelite_500x500.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x6e: RazerDeviceInfo(
        name: 'Razer DeathAdder Essential',
        productId: 0x6e,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1385/1385_deathadderessential.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 6400)
        }),
    0x98: RazerDeviceInfo(
        name: 'Razer DeathAdder Essential (2021)',
        productId: 0x98,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1385/1385_deathadderessential.png',
        missingFeatures: {},
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 6400)
        }),
    0x71: RazerDeviceInfo(
        name: 'Razer DeathAdder Essential (White Edition)',
        productId: 0x71,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets2.razerzone.com/images/da10m/carousel/razer-death-adder-gallery-25.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 6400)
        }),
    0x84: RazerDeviceInfo(
        name: 'Razer DeathAdder V2',
        productId: 0x84,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1612/1612_razerdeathadderv2.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.oldMouseEffects
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false)
        }),
    0x8c: RazerDeviceInfo(
        name: 'Razer DeathAdder V2 Mini',
        productId: 0x8c,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1692/deathadder-v2-mini.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.oldMouseEffects
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 8500)
        }),
    0x7c: RazerDeviceInfo(
        name: 'Razer DeathAdder V2 Pro Wired',
        productId: 0x7c,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1714/comp_1_00000.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.oldMouseEffects
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledLeft: false,
              enabledRight: false,
              enabledScroll: false)
        }),
    0x7d: RazerDeviceInfo(
        name: 'Razer DeathAdder V2 Pro Wireless',
        productId: 0x7d,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1714/comp_1_00000.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple,
          OptionalRazerDeviceFeature.oldMouseEffects
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledLeft: false,
              enabledRight: false,
              enabledScroll: false)
        }),
    0x204: RazerDeviceInfo(
        name: 'Razer Deathstalker Chroma',
        productId: 0x204,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/665/665_deathstalker_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 1, cols: 6),
          WheelFeatureConfig: WheelFeatureConfig(rows: 1, cols: 6)
        }),
    0x202: RazerDeviceInfo(
        name: 'Razer Deathstalker Expert',
        productId: 0x202,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/49/49_razer_deathstalker.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x4c: RazerDeviceInfo(
        name: 'Razer Diamondback Chroma',
        productId: 0x4c,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/613/613_diamondback.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 16000)}),
    0xc00: RazerDeviceInfo(
        name: 'Razer Firefly',
        productId: 0xc00,
        mainType: RazerDeviceType.mousemat,
        image:
            'https://assets.razerzone.com/eeimages/support/products/594/594_firefly_500x500.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x68: RazerDeviceInfo(
        name: 'Razer Firefly Hyperflux',
        productId: 0x68,
        mainType: RazerDeviceType.mousemat,
        image:
            'https://assets.razerzone.com/eeimages/support/products/594/594_firefly_500x500.png',
        missingFeatures: {},
        featureConfigs: {}),
    0xc04: RazerDeviceInfo(
        name: 'Razer Firefly V2',
        productId: 0xc04,
        mainType: RazerDeviceType.mousemat,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1594/1594_firefly_v2.png',
        missingFeatures: {},
        featureConfigs: {}),
    0xc01: RazerDeviceInfo(
        name: 'Razer Goliathus Chroma',
        productId: 0xc01,
        mainType: RazerDeviceType.mousemat,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1394/1394_goliathus_chroma.png',
        missingFeatures: {},
        featureConfigs: {}),
    0xc02: RazerDeviceInfo(
        name: 'Razer Goliathus Chroma Extended',
        productId: 0xc02,
        mainType: RazerDeviceType.mousemat,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1395/1395_goliathusextended.png',
        missingFeatures: {OptionalRazerDeviceFeature.waveSimple},
        featureConfigs: {}),
    0x227: RazerDeviceInfo(
        name: 'Razer Huntsman',
        productId: 0x227,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1360/1360_huntsman-3.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x226: RazerDeviceInfo(
        name: 'Razer Huntsman Elite',
        productId: 0x226,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1361/1361_huntsman_elite.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 9, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 9, cols: 22)
        }),
    0x257: RazerDeviceInfo(
        name: 'Razer Huntsman Mini',
        productId: 0x257,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1689/1689-huntsmanmini.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 5, cols: 15),
          WheelFeatureConfig: WheelFeatureConfig(rows: 5, cols: 15)
        }),
    0x269: RazerDeviceInfo(
        name: 'Razer Huntsman Mini (JP)',
        productId: 0x269,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://rzrwarranty.s3.amazonaws.com/4403e5e6b96d59dc95a278e257688e64a68f7b24945617653d68e3273877c01e.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 5, cols: 15),
          WheelFeatureConfig: WheelFeatureConfig(rows: 5, cols: 15)
        }),
    0x243: RazerDeviceInfo(
        name: 'Razer Huntsman Tournament Edition',
        productId: 0x243,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1537/1537_huntsman_te.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 18),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 18)
        }),
    0x26c: RazerDeviceInfo(
        name: 'Razer Huntsman V2',
        productId: 0x26c,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets3.razerzone.com/QYslx_0_W5a9v8kaW2k-eHQ3DMA=/300x300/https%3A%2F%2Fhybrismediaprod.blob.core.windows.net%2Fsys-master-phoenix-images-container%2Fh61%2Fhd7%2F9239675633694%2Fhuntsman-v2-500x500.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x266: RazerDeviceInfo(
        name: 'Razer Huntsman V2 Analog',
        productId: 0x266,
        mainType: RazerDeviceType.keyboard,
        image: 'https://dl.razerzone.com/src/4023-1-EN-v1.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 9, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 9, cols: 22)
        }),
    0x26b: RazerDeviceInfo(
        name: 'Razer Huntsman V2 TKL',
        productId: 0x26b,
        mainType: RazerDeviceType.keyboard,
        image: 'https://dl.razerzone.com/src/5638/5638-1-en-v1.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 18),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 18)
        }),
    0x2f: RazerDeviceInfo(
        name: 'Razer Imperator',
        productId: 0x2f,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/215/215_imperator.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 6400)}),
    0x504: RazerDeviceInfo(
        name: 'Razer Kraken 7.1 Chroma',
        productId: 0x504,
        mainType: RazerDeviceType.headphone,
        image:
            'https://assets.razerzone.com/eeimages/support/products/280/280_kraken_71_chroma.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x501: RazerDeviceInfo(
        name: 'Razer Kraken 7.1',
        productId: 0x501,
        mainType: RazerDeviceType.headphone,
        image:
            'https://assets.razerzone.com/eeimages/support/products/229/229_kraken_71.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x506: RazerDeviceInfo(
        name: 'Razer Kraken 7.1',
        productId: 0x506,
        mainType: RazerDeviceType.headphone,
        image:
            'https://assets.razerzone.com/eeimages/support/products/229/229_kraken_71.png',
        missingFeatures: {},
        featureConfigs: {}),
    0xf19: RazerDeviceInfo(
        name: 'Razer Kraken Kitty Edition',
        productId: 0xf19,
        mainType: RazerDeviceType.headphone,
        image:
            'https://assets2.razerzone.com/images/pnx.assets/1c503aa176bc82d999299aba0d6c7d2c/kraken-kitty-quartz.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x527: RazerDeviceInfo(
        name: 'Razer Kraken Ultimate',
        productId: 0x527,
        mainType: RazerDeviceType.headphone,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1603/rzr_kraken_ultimate_render01_2019_resized.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x510: RazerDeviceInfo(
        name: 'Razer Kraken V2',
        productId: 0x510,
        mainType: RazerDeviceType.headphone,
        image:
            'https://assets.razerzone.com/eeimages/support/products/729/729_kraken_71_v2.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x60: RazerDeviceInfo(
        name: 'Razer Lancehead Tournament Edition',
        productId: 0x60,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1203/1206_lanceheadte.png',
        missingFeatures: {},
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledScroll: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x59: RazerDeviceInfo(
        name: 'Razer Lancehead Wired',
        productId: 0x59,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1205/1205_lancehead.png',
        missingFeatures: {},
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledScroll: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x5a: RazerDeviceInfo(
        name: 'Razer Lancehead Wireless',
        productId: 0x5a,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1205/1205_lancehead.png',
        missingFeatures: {},
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledScroll: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x6f: RazerDeviceInfo(
        name: 'Razer Lancehead (Receiver)',
        productId: 0x6f,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1205/1205_lancehead.png',
        missingFeatures: {},
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledScroll: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x70: RazerDeviceInfo(
        name: 'Razer Lancehead Wireless Wired',
        productId: 0x70,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1527/lancehead_wireless_2018_render_squared.png',
        missingFeatures: {},
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledScroll: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x24: RazerDeviceInfo(
        name: 'Razer Mamba 2012 Wired',
        productId: 0x24,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/192/192_mamba_2012.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledLogo: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 6400)
        }),
    0x25: RazerDeviceInfo(
        name: 'Razer Mamba 2012 Wireless',
        productId: 0x25,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/192/192_mamba_2012.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledLogo: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 6400)
        }),
    0x6c: RazerDeviceInfo(
        name: 'Razer Mamba Elite',
        productId: 0x6c,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1390/1390_mamba_elite.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.oldMouseEffects,
          OptionalRazerDeviceFeature.battery
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 16000),
          MouseBrightnessFeatureConfig:
              MouseBrightnessFeatureConfig(enabledMatrix: false)
        }),
    0x46: RazerDeviceInfo(
        name: 'Razer Mamba Tournament Edition',
        productId: 0x46,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/606/606_mambate_500x500.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {}),
    0x44: RazerDeviceInfo(
        name: 'Razer Mamba Wired',
        productId: 0x44,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/609/609_mamba_500x500.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 16000)}),
    0x45: RazerDeviceInfo(
        name: 'Razer Mamba Wireless',
        productId: 0x45,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1404/1404_mamba_wireless.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x72: RazerDeviceInfo(
        name: 'Razer Mamba (Receiver)',
        productId: 0x72,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1404/1404_mamba_wireless.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x73: RazerDeviceInfo(
        name: 'Razer Mamba Wireless Wired',
        productId: 0x73,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1404/1404_mamba_wireless.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0xf1d: RazerDeviceInfo(
        name: 'Razer Mouse Bungee V3 Chroma',
        productId: 0xf1d,
        mainType: RazerDeviceType.accessory,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1737/3847-3-en-v1.jpg',
        missingFeatures: {},
        featureConfigs: {}),
    0x7e: RazerDeviceInfo(
        name: 'Razer Mouse Charging Dock',
        productId: 0x7e,
        mainType: RazerDeviceType.mousedock,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1711/1711_-_mouse_dock_chroma.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x2e: RazerDeviceInfo(
        name: 'Razer Naga 2012',
        productId: 0x2e,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/products/39/razer-naga-gallery-4.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 5600)}),
    0x40: RazerDeviceInfo(
        name: 'Razer Naga 2014',
        productId: 0x40,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/227/227_razer_naga_2014.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 8200)}),
    0x53: RazerDeviceInfo(
        name: 'Razer Naga Chroma',
        productId: 0x53,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/636/636_naga_chroma.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x41: RazerDeviceInfo(
        name: 'Razer Naga Hex',
        productId: 0x41,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/23/23_naga_hex.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 5600)}),
    0x36: RazerDeviceInfo(
        name: 'Razer Naga Hex (Red)',
        productId: 0x36,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/products/12/razer-naga-hex-gallery-12.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 5600)}),
    0x50: RazerDeviceInfo(
        name: 'Razer Naga Hex V2',
        productId: 0x50,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/715/715_nagahexv2_500x500.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false, enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x8d: RazerDeviceInfo(
        name: 'Razer Naga Left Handed Edition 2020',
        productId: 0x8d,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1704/product.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.oldMouseEffects
        },
        featureConfigs: {
          DpiFeatureConfig: DpiFeatureConfig(max: 20000),
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false, enabledLeft: false)
        }),
    0x8f: RazerDeviceInfo(
        name: 'Razer Naga Pro - Wired',
        productId: 0x8f,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1710/small_product.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.oldMouseEffects,
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledLogo: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 20000)
        }),
    0x90: RazerDeviceInfo(
        name: 'Razer Naga Pro - Wireless',
        productId: 0x90,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1710/small_product.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.oldMouseEffects,
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledLogo: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 20000)
        }),
    0x67: RazerDeviceInfo(
        name: 'Razer Naga Trinity',
        productId: 0x67,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1251/1251_razer_naga_trinity.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledLogo: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x517: RazerDeviceInfo(
        name: 'Razer Nommo Chroma',
        productId: 0x517,
        mainType: RazerDeviceType.accessory,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1275/1275_nommo_chroma.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x518: RazerDeviceInfo(
        name: 'Razer Nommo Pro',
        productId: 0x518,
        mainType: RazerDeviceType.accessory,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1419/1419_nommo_pro.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x111: RazerDeviceInfo(
        name: 'Razer Nostromo',
        productId: 0x111,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/564/564_tartarus_classic.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x113: RazerDeviceInfo(
        name: 'Razer Orbweaver',
        productId: 0x113,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/56/56_orbweaver.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x207: RazerDeviceInfo(
        name: 'Razer Orbweaver Chroma',
        productId: 0x207,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/607/607_orbweaver_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 5, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 5, cols: 22)
        }),
    0x21f: RazerDeviceInfo(
        name: 'Razer Ornata',
        productId: 0x21f,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/726/726_ornata.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x21e: RazerDeviceInfo(
        name: 'Razer Ornata Chroma',
        productId: 0x21e,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/727/727_ornata_chroma.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x25d: RazerDeviceInfo(
        name: 'Razer Ornata V2',
        productId: 0x25d,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1672/ornata-v2.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 6, cols: 22),
          WheelFeatureConfig: WheelFeatureConfig(rows: 6, cols: 22)
        }),
    0x13: RazerDeviceInfo(
        name: 'Razer Orochi 2011',
        productId: 0x13,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/612/612_orochi_2015.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 4000)}),
    0x39: RazerDeviceInfo(
        name: 'Razer Orochi 2013',
        productId: 0x39,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/612/612_orochi_2015.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 6400)}),
    0x48: RazerDeviceInfo(
        name: 'Razer Orochi Chroma',
        productId: 0x48,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/612/612_orochi_2015.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 8200)}),
    0x95: RazerDeviceInfo(
        name: 'Razer Orochi V2 (Bluetooth)',
        productId: 0x95,
        mainType: RazerDeviceType.mouse,
        image: 'https://dl.razerzone.com/src/OrochiV2-1-en-v1.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 18000)}),
    0x94: RazerDeviceInfo(
        name: 'Razer Orochi Chroma (Receiver)',
        productId: 0x94,
        mainType: RazerDeviceType.mouse,
        image: 'https://dl.razerzone.com/src/OrochiV2-1-en-v1.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 18000)}),
    0x32: RazerDeviceInfo(
        name: 'Razer Ouroboros',
        productId: 0x32,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/26/26_ouroboros.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledLogo: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 8200)
        }),
    0x34: RazerDeviceInfo(
        name: 'Razer Taipan',
        productId: 0x34,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/19/19_taipan.png',
        missingFeatures: {OptionalRazerDeviceFeature.mouseBrightness},
        featureConfigs: {DpiFeatureConfig: DpiFeatureConfig(max: 8200)}),
    0x201: RazerDeviceInfo(
        name: 'Razer Tartarus',
        productId: 0x201,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/228/228_tartarus.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x208: RazerDeviceInfo(
        name: 'Razer Tartarus Chroma',
        productId: 0x208,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/598/598_tartarus_chroma.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.ripple,
          OptionalRazerDeviceFeature.wheel
        },
        featureConfigs: {}),
    0x22b: RazerDeviceInfo(
        name: 'Razer Tartarus V2',
        productId: 0x22b,
        mainType: RazerDeviceType.keyboard,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1255/1255_tartarus_v2.png',
        missingFeatures: {},
        featureConfigs: {
          RippleFeatureConfig: RippleFeatureConfig(rows: 4, cols: 6),
          WheelFeatureConfig: WheelFeatureConfig(rows: 4, cols: 6)
        }),
    0xf21: RazerDeviceInfo(
        name: 'Razer Thunderbolt 4 Dock Chroma',
        productId: 0xf21,
        mainType: RazerDeviceType.accessory,
        image: 'https://dl.razerzone.com/src/4030-1-EN-v1.png',
        missingFeatures: {},
        featureConfigs: {}),
    0x78: RazerDeviceInfo(
        name: 'Razer Viper',
        productId: 0x78,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1539/1539_viper.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 16000)
        }),
    0x91: RazerDeviceInfo(
        name: 'Razer Viper 8Khz',
        productId: 0x91,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1755/viper8khz.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 20000)
        }),
    0x8a: RazerDeviceInfo(
        name: 'Razer Viper Mini',
        productId: 0x8a,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1634/vipermini.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 8500)
        }),
    0x7a: RazerDeviceInfo(
        name: 'Razer Viper Ultimate Wired',
        productId: 0x7a,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1577/ee_photo.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 20000)
        }),
    0x7b: RazerDeviceInfo(
        name: 'Razer Viper Ultimate Wireless',
        productId: 0x7b,
        mainType: RazerDeviceType.mouse,
        image:
            'https://assets.razerzone.com/eeimages/support/products/1577/ee_photo.png',
        missingFeatures: {
          OptionalRazerDeviceFeature.waveSimple
        },
        featureConfigs: {
          MouseBrightnessFeatureConfig: MouseBrightnessFeatureConfig(
              enabledMatrix: false,
              enabledScroll: false,
              enabledLeft: false,
              enabledRight: false),
          DpiFeatureConfig: DpiFeatureConfig(max: 20000)
        })
  };
}
