// ignore_for_file: type=lint

// Generated file; DO NOT EDIT!
// Generated by tools/generate_razer_keys.dart on 2022-07-14 16:03:18.302971Z.

enum RazerKey {
  /// Esc (VK_ESCAPE)
  esc(0, 1),

  /// F1 (VK_F1)
  f1(0, 3),

  /// F2 (VK_F2)
  f2(0, 4),

  /// F3 (VK_F3)
  f3(0, 5),

  /// F4 (VK_F4)
  f4(0, 6),

  /// F5 (VK_F5)
  f5(0, 7),

  /// F6 (VK_F6)
  f6(0, 8),

  /// F7 (VK_F7)
  f7(0, 9),

  /// F8 (VK_F8)
  f8(0, 10),

  /// F9 (VK_F9)
  f9(0, 11),

  /// F10 (VK_F10)
  f10(0, 12),

  /// F11 (VK_F11)
  f11(0, 13),

  /// F12 (VK_F12)
  f12(0, 14),

  /// 1 (VK_1)
  one(1, 2),

  /// 2 (VK_2)
  two(1, 3),

  /// 3 (VK_3)
  three(1, 4),

  /// 4 (VK_4)
  four(1, 5),

  /// 5 (VK_5)
  five(1, 6),

  /// 6 (VK_6)
  six(1, 7),

  /// 7 (VK_7)
  seven(1, 8),

  /// 8 (VK_8)
  eight(1, 9),

  /// 9 (VK_9)
  nine(1, 10),

  /// 0 (VK_0)
  zero(1, 11),

  /// A (VK_A)
  a(3, 2),

  /// B (VK_B)
  b(4, 7),

  /// C (VK_C)
  c(4, 5),

  /// D (VK_D)
  d(3, 4),

  /// E (VK_E)
  e(2, 4),

  /// F (VK_F)
  f(3, 5),

  /// G (VK_G)
  g(3, 6),

  /// H (VK_H)
  h(3, 7),

  /// I (VK_I)
  i(2, 9),

  /// J (VK_J)
  j(3, 8),

  /// K (VK_K)
  k(3, 9),

  /// L (VK_L)
  l(3, 10),

  /// M (VK_M)
  m(4, 9),

  /// N (VK_N)
  n(4, 8),

  /// O (VK_O)
  o(2, 10),

  /// P (VK_P)
  p(2, 11),

  /// Q (VK_Q)
  q(2, 2),

  /// R (VK_R)
  r(2, 5),

  /// S (VK_S)
  s(3, 3),

  /// T (VK_T)
  t(2, 6),

  /// U (VK_U)
  u(2, 8),

  /// V (VK_V)
  v(4, 6),

  /// W (VK_W)
  w(2, 3),

  /// X (VK_X)
  x(4, 4),

  /// Y (VK_Y)
  y(2, 7),

  /// Z (VK_Z)
  z(4, 3),

  /// Numlock (VK_NUMLOCK)
  numlock(1, 18),

  /// Numpad 0 (VK_NUMPAD0)
  numpad0(5, 19),

  /// Numpad 1 (VK_NUMPAD1)
  numpad1(4, 18),

  /// Numpad 2 (VK_NUMPAD2)
  numpad2(4, 19),

  /// Numpad 3 (VK_NUMPAD3)
  numpad3(4, 20),

  /// Numpad 4 (VK_NUMPAD4)
  numpad4(3, 18),

  /// Numpad 5 (VK_NUMPAD5)
  numpad5(3, 19),

  /// Numpad 6 (VK_NUMPAD6)
  numpad6(3, 20),

  /// Numpad 7 (VK_NUMPAD7)
  numpad7(2, 18),

  /// Numpad 8 (VK_NUMPAD8)
  numpad8(2, 19),

  /// Numpad 9 (VK_ NUMPAD9.
  numpad9(2, 20),

  /// Divide (VK_DIVIDE)
  numpadDivide(1, 19),

  /// Multiply (VK_MULTIPLY)
  numpadMultiply(1, 20),

  /// Subtract (VK_SUBTRACT)
  numpadSubtract(1, 21),

  /// Add (VK_ADD)
  numpadAdd(2, 21),

  /// Enter (VK_RETURN - Extended)
  numpadEnter(4, 21),

  /// Decimal (VK_DECIMAL)
  numpadDecimal(5, 20),

  /// Print Screen (VK_PRINT)
  printscreen(0, 15),

  /// Scroll Lock (VK_SCROLL)
  scroll(0, 16),

  /// Pause (VK_PAUSE)
  pause(0, 17),

  /// Insert (VK_INSERT)
  insert(1, 15),

  /// Home (VK_HOME)
  home(1, 16),

  /// Page Up (VK_PRIOR)
  pageup(1, 17),

  /// Delete (VK_DELETE)
  delete(2, 15),

  /// End (VK_END)
  end(2, 16),

  /// Page Down (VK_NEXT)
  pagedown(2, 17),

  /// Up (VK_UP)
  up(4, 16),

  /// Left (VK_LEFT)
  left(5, 15),

  /// Down (VK_DOWN)
  down(5, 16),

  /// Right (VK_RIGHT)
  right(5, 17),

  /// Tab (VK_TAB)
  tab(2, 1),

  /// Caps Lock(VK_CAPITAL)
  capslock(3, 1),

  /// Backspace (VK_BACK)
  backspace(1, 14),

  /// Enter (VK_RETURN)
  enter(3, 14),

  /// Left Control(VK_LCONTROL)
  lctrl(5, 1),

  /// Left Window (VK_LWIN)
  lwin(5, 2),

  /// Left Alt (VK_LMENU)
  lalt(5, 3),

  /// Spacebar (VK_SPACE)
  space(5, 7),

  /// Right Alt (VK_RMENU)
  ralt(5, 11),

  /// Function key.
  fn(5, 12),

  /// Right Menu (VK_APPS)
  rmenu(5, 13),

  /// Right Control (VK_RCONTROL)
  rctrl(5, 14),

  /// Left Shift (VK_LSHIFT)
  lshift(4, 1),

  /// Right Shift (VK_RSHIFT)
  rshift(4, 14),

  /// Macro Key 1.
  macro1(1, 0),

  /// Macro Key 2.
  macro2(2, 0),

  /// Macro Key 3.
  macro3(3, 0),

  /// Macro Key 4.
  macro4(4, 0),

  /// Macro Key 5.
  macro5(5, 0),

  /// ~ (tilde/半角/全角) (VK_OEM_3)
  oem1(1, 1),

  /// – (minus) (VK_OEM_MINUS)
  oem2(1, 12),

  /// = (equal) (VK_OEM_PLUS)
  oem3(1, 13),

  /// [ (left sqaure bracket) (VK_OEM_4)
  oem4(2, 12),

  /// ] (right square bracket) (VK_OEM_6)
  oem5(2, 13),

  /// \ (backslash) (VK_OEM_5)
  oem6(2, 14),

  /// ; (semi-colon) (VK_OEM_1)
  oem7(3, 11),

  /// ' (apostrophe) (VK_OEM_7)
  oem8(3, 12),

  /// , (comma) (VK_OEM_COMMA)
  oem9(4, 10),

  /// . (period) (VK_OEM_PERIOD)
  oem10(4, 11),

  /// / (forward slash) (VK_OEM_2)
  oem11(4, 12),

  /// "#" (VK_OEM_5)
  eur1(3, 13),

  /// \ (VK_OEM_102)
  eur2(4, 2),

  /// ¥ (0xFF)
  jpn1(0, 21),

  /// \ (0xC1)
  jpn2(4, 13),

  /// 無変換 (VK_OEM_PA1)
  jpn3(5, 4),

  /// 変換 (0xFF)
  jpn4(5, 9),

  /// ひらがな/カタカナ (0xFF)
  jpn5(5, 10),

  /// | (0xFF)
  kor1(0, 21),

  /// (VK_OEM_5)
  kor2(3, 13),

  /// (VK_OEM_102)
  kor3(4, 2),

  /// (0xC1)
  kor4(4, 13),

  /// (VK_OEM_PA1)
  kor5(5, 4),

  /// 한/영 (0xFF)
  kor6(5, 9),

  /// (0xFF)
  kor7(5, 10);

  const RazerKey(this.row, this.column);

  final int row;

  final int column;

  static const rowCount = 6;

  static const columnCount = 22;

  static const layout = <List<Set<RazerKey>>>[
    [
      {},
      {RazerKey.esc},
      {},
      {RazerKey.f1},
      {RazerKey.f2},
      {RazerKey.f3},
      {RazerKey.f4},
      {RazerKey.f5},
      {RazerKey.f6},
      {RazerKey.f7},
      {RazerKey.f8},
      {RazerKey.f9},
      {RazerKey.f10},
      {RazerKey.f11},
      {RazerKey.f12},
      {RazerKey.printscreen},
      {RazerKey.scroll},
      {RazerKey.pause},
      {},
      {},
      {},
      {RazerKey.jpn1, RazerKey.kor1}
    ],
    [
      {RazerKey.macro1},
      {RazerKey.oem1},
      {RazerKey.one},
      {RazerKey.two},
      {RazerKey.three},
      {RazerKey.four},
      {RazerKey.five},
      {RazerKey.six},
      {RazerKey.seven},
      {RazerKey.eight},
      {RazerKey.nine},
      {RazerKey.zero},
      {RazerKey.oem2},
      {RazerKey.oem3},
      {RazerKey.backspace},
      {RazerKey.insert},
      {RazerKey.home},
      {RazerKey.pageup},
      {RazerKey.numlock},
      {RazerKey.numpadDivide},
      {RazerKey.numpadMultiply},
      {RazerKey.numpadSubtract}
    ],
    [
      {RazerKey.macro2},
      {RazerKey.tab},
      {RazerKey.q},
      {RazerKey.w},
      {RazerKey.e},
      {RazerKey.r},
      {RazerKey.t},
      {RazerKey.y},
      {RazerKey.u},
      {RazerKey.i},
      {RazerKey.o},
      {RazerKey.p},
      {RazerKey.oem4},
      {RazerKey.oem5},
      {RazerKey.oem6},
      {RazerKey.delete},
      {RazerKey.end},
      {RazerKey.pagedown},
      {RazerKey.numpad7},
      {RazerKey.numpad8},
      {RazerKey.numpad9},
      {RazerKey.numpadAdd}
    ],
    [
      {RazerKey.macro3},
      {RazerKey.capslock},
      {RazerKey.a},
      {RazerKey.s},
      {RazerKey.d},
      {RazerKey.f},
      {RazerKey.g},
      {RazerKey.h},
      {RazerKey.j},
      {RazerKey.k},
      {RazerKey.l},
      {RazerKey.oem7},
      {RazerKey.oem8},
      {RazerKey.eur1, RazerKey.kor2},
      {RazerKey.enter},
      {},
      {},
      {},
      {RazerKey.numpad4},
      {RazerKey.numpad5},
      {RazerKey.numpad6}
    ],
    [
      {RazerKey.macro4},
      {RazerKey.lshift},
      {RazerKey.eur2, RazerKey.kor3},
      {RazerKey.z},
      {RazerKey.x},
      {RazerKey.c},
      {RazerKey.v},
      {RazerKey.b},
      {RazerKey.n},
      {RazerKey.m},
      {RazerKey.oem9},
      {RazerKey.oem10},
      {RazerKey.oem11},
      {RazerKey.jpn2, RazerKey.kor4},
      {RazerKey.rshift},
      {},
      {RazerKey.up},
      {},
      {RazerKey.numpad1},
      {RazerKey.numpad2},
      {RazerKey.numpad3},
      {RazerKey.numpadEnter}
    ],
    [
      {RazerKey.macro5},
      {RazerKey.lctrl},
      {RazerKey.lwin},
      {RazerKey.lalt},
      {RazerKey.jpn3, RazerKey.kor5},
      {},
      {},
      {RazerKey.space},
      {},
      {RazerKey.jpn4, RazerKey.kor6},
      {RazerKey.jpn5, RazerKey.kor7},
      {RazerKey.ralt},
      {RazerKey.fn},
      {RazerKey.rmenu},
      {RazerKey.rctrl},
      {RazerKey.left},
      {RazerKey.down},
      {RazerKey.right},
      {},
      {RazerKey.numpad0},
      {RazerKey.numpadDecimal}
    ]
  ];
}
